version: '2'
services:
  
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: es
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
          - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
    depends_on:
      - es
